
import { Provider } from 'react-redux';
import Head from 'next/head'
import { useRouter } from 'next/router';

import store from '../redux/store';
import LayoutWrapper from '../components/layout';
import { getResolvedFinalPath, getResolvedPaths } from '../helpers/routingPathHelper';
import { getVerifiedSession } from '../helpers/sessionHelper';

import "../styles/globals.css";

function MyApp({ Component, pageProps }) {

  const router = useRouter();
  const finalResolvedPath = getResolvedFinalPath(router);
  const session = getVerifiedSession();
  const resolvedPaths = getResolvedPaths(router);
  console.log('session', session);

  return (
    <Provider store={store}>
      <LayoutWrapper router={router} resolvedPaths={resolvedPaths} session={session} >
        <Head>
          <title>{getResolvedFinalPath(router)}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/webclip.png" />
        </Head>
        <Component finalResolvedPath={finalResolvedPath} session={session} resolvedPaths={resolvedPaths} {...pageProps} />
      </LayoutWrapper>
    </Provider>);
}

export default MyApp
