
import { Provider } from 'react-redux';
import Head from 'next/head'

import store from '../redux/store';
import LayoutWrapper from '../components/layout';
import "../styles/globals.css";

function MyApp({ Component, pageProps }) {

  return (
    <Provider store={store}>
      <LayoutWrapper>
        <Head>
          <title>Lay out</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/webclip.png" />
        </Head>
        <Component {...pageProps} />
      </LayoutWrapper>
    </Provider>);
}

export default MyApp
